# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-23 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_qz_zf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qz',
            name='age',
            field=models.IntegerField(verbose_name='\u5e74\u9f84'),
        ),
        migrations.AlterField(
            model_name='zf',
            name='age',
            field=models.IntegerField(verbose_name='\u5e74\u9f84'),
        ),
    ]
