# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-05 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20170505_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='\u6807\u9898')),
                ('img_file', models.ImageField(upload_to='imgs', verbose_name='\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u5bb6\u5177\u8be6\u60c5',
                'verbose_name_plural': '\u5bb6\u5177\u8be6\u60c5',
            },
        ),
        migrations.AlterField(
            model_name='furnituretype',
            name='enable',
            field=models.IntegerField(choices=[(1, '\u662f'), (0, '\u5426')], default=1, verbose_name='\u662f\u5426\u542f\u7528'),
        ),
    ]
